### ISSUE TITLE
希望能出个AE转换插件，支持转换字节的AE插件制作的MP4动画

### ISSUE THREAD

**Issue by sangxb** [yylive/YYEVA-Android#2]
如果能有AE转换插件直接，将字节库制作的mp4动画转化成YYEVA需要的格式，对YYEVA成为以后行业标杆有极大帮助。对第三方接入者也是福利：

1. 美术无需重新制作 MP4动画，减少美术工作量；
2. 开发直接删除 字节跳动的依赖库，减少业务逻辑的兼容操作和包体积优化

节省的这些时间，精力对于任何团队来说那都是再省钱啊！！！
另外附上字节库的地址，方便你们查阅哈：https://github.com/bytedance/AlphaPlayer

最后祝愿 YYEVA 早日成为行业标杆哈

**Comment by cangwang** [comment]
后续的方案，我们有可能直接检测字节的mp4的透明布局方向，然后直接进行解析播放。不需要AE插件转换，但是播放检测会有一定耗时。

**Comment by sangxb** [comment]
能直接播放当然是最好的，字节库的透明度的布局和你们是相反的，现在也能播放就是说会有蒙版看着灰突突的 -_-#
